// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:brasil_card/domain/entities/crypto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoAdapter());
  }
}
